### ISSUE TITLE
After cloning and trying to run tests on VSCode or IntelliJ I get: Unable to find runtime dependencies beginning with: 'guava'

### ISSUE THREAD

**Issue by ricmrodrigues** [moderneinc/rewrite-recipe-starter#15]
![image](https://user-images.githubusercontent.com/241161/219964727-85b36222-7688-4a8e-95d2-7588213a3675.png)

```
java.lang.IllegalArgumentException: Unable to find runtime dependencies beginning with: 'guava'
 at org.openrewrite.java.JavaParser.dependenciesFromClasspath(JavaParser.java:104)
 at org.openrewrite.java.JavaParser$Builder.classpath(JavaParser.java:346)
 at com.yourorg.NoGuavaListsNewArrayListTest.defaults(NoGuavaListsNewArrayListTest.java:20)
 at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:136)
 at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
 at com.yourorg.NoGuavaListsNewArrayListTest.replaceWithNewArrayList(NoGuavaListsNewArrayListTest.java:25)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
```

**Comment by timtebeek** [comment]
Fixed through #16 ; thanks again!
